config/routes.rb
Turnt::Application.routes.draw do

   root 'welcome#index'
     resources :users do
   end 

   resources :games do
     resources :scores
   end

   get 'search' => 'games#search'
   post 'players' => 'users#search'
   
   get 'login' => 'sessions#new'
   post 'creation' => 'sessions#create'
   delete 'destroy' => 'sessions#destroy'

  

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :scores
  has_many :players, through: :scores, source: :user
  belongs_to :winner, class_name: "User"
  before_save :set_values

  def two_players
    self.players.length  >= 2
  end

  def set_values
  	self.commodity ||= 0
  	self.real_estate ||= 0
  	self.bond ||= 0
  	self.stock ||= 0
  end	
  
end

app/models/score.rb
class Score < ActiveRecord::Base
  belongs_to :user
  belongs_to :game
  validates :user_id, presence: true
  validates :game_id, presence: true
  before_save :set_values

  def stock_net
  	self.stocks * self.game.stock
  end  

  def bond_net
  	self.bonds * self.game.bond
  end

  def real_estate_net
  	self.real_estates * self.game.real_estate
  end

  def commodity_net
  	self.commodities * self.game.commodity
  end

  def net
    self.commodity_net + 
    self.real_estate_net + 
    self.bond_net + 
    self.stock_net + 
    self.cash
  end	

  def set_values
    self.accepted ||= false
    self.commodities ||= 0
    self.real_estates ||= 0
    self.bonds ||= 0
    self.stocks ||= 0
    self.cash ||=500
  end 

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :scores
  has_many :played_games, through: :scores, source: :game
  has_many :victories, class_name: "Game", foreign_key: :winner_id
  validates :username, length: { minimum: 5 }
  validates :password, length: { minimum: 5 }
  validates_format_of :email, :with => /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/
  has_secure_password
  
  def finished_games
  	finished_gs=[]
    self.scores.each do |s|
      if s.game.winner_id != nil
      	finished_gs << s
      end	
    end
    finished_gs
  end	

  def ongoing
    ogames=[]
    accepted = self.scores.where(accepted:true)
    p accepted
    accepted.each do |s|
      if s.game.winner_id == nil
        ogames << s
      end 
    end
    ogames
  end  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    current_user ||= User.find(session[:user_id]) if session[:user_id]
  end  
  
  helper_method :current_user
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
   @games =Game.where(name: params['q'])
   
  end	

  def show
    @game=Game.find(params[:id])
    @players=@game.players
    @user=@players.first
  end	

  def new
  	@game= Game.new
  end

  def create
    @game=Game.create(name: params[:name])
    @user= current_user
    @score=Score.create(user_id:@user.id, game_id:@game.id, accepted:true )
    redirect_to(game_path(@game))
  end  

  def search
    
  end	
  
end	

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
	def show
      @game= Game.find(params[:game_id])
      @invitation=Invitation.find(params[:id])
      @players=@game.players
	end	

	def update
      @game= Game.find(params[:game_id])
      @invitation=Invitation.find(params[:id])
      @invitation.update_attributes(started: true)
      Score.create(user_id: @invitation.user_id, Game.id)
      redirect_to game_scores_path(@invitation.user.id)
      # redirect_to :controller=>'scores',:action=>'create'
	end	
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  def new
  end	


  def create
    Score.create(game_id:params["game_id"],user_id:params["user_id"])
    redirect_to game_path(params["game_id"])
  end

  def update
    @game= Game.find(params[:game_id])
    @score= Score.find(params[:id])
    @score.update_attributes(accepted: true)
    redirect_to game_path(@game.id)
  end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user=User.new
  end

  def create
    
    @user= User.find_by_email(params['sessions']['email'])
    if @user 
      if @user.authenticate(params[:sessions][:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
      else
        @error="Incorrect Password"
        render template: "sessions/new"
      end    
    else
      @error="no registered email under that address"
      render template: "sessions/new"
    end     
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end  


end  

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
   @user = User.new
  end

  def create
    @user= User.new(username: params[:user][:username],email: params[:user][:email],password: params[:user][:password],password_confirmation: params[:user][:password])
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render template: "users/new"
    end  
  end

  def show
    @user = User.find(params[:id])
    @ongoing = @user.ongoing
    @requests = @user.scores.where(accepted: false)
    @finished =@user.finished_games
    @scores = @user.scores
  end  

  def search
    @game = Game.find(params["game"])
    @players = @game.players
    @users = User.where(username:params[:username])
  
  end  
  
end
		

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@home_page = true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/new.html.erb
<%= form_tag(games_path) do %>
  <%= label_tag(:name, "Game Name") %>
  <%= text_field_tag(:name) %>
  <%= submit_tag("Create a Game") %>
<% end %>

app/views/games/search.html.erb
<%= form_tag("/games", method: "get") do %>
  <%= label_tag(:q, "Search for games:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>

app/views/games/show.html.erb
<%= @game.name%>
<% if @players.length == 1%>
<h1>Invite People</h1>
<%= form_tag("/players") do %>
  <%= label_tag(:q, "Search for users:") %>
  <%= text_field_tag(:username) %>
  <%= hidden_field_tag(:game, @game.id)%>
  <%= submit_tag("Search") %>
<% end %>
<% else %>
<h1>Invite Some More People</h1>
<%= form_tag("/players") do %>
  <%= label_tag(:q, "Search for users:") %>
  <%= text_field_tag(:username) %>
  <%= hidden_field_tag(:game, @game.id)%>
  <%= submit_tag("Search") %>
<% end %>

<table class="player">
  <thead>
    <tr class="users">
      <th>Players</th>
      <%@players.each do |p|%>
      <th><%= p.username%>
      <%if p.scores.find_by_game_id(@game.id).accepted != true  %>
        <span class="unaccepted"><%= "Unaccepted" %></span>
      <% end %>  
      </th>
      <% end%>  
    </tr>
 </thead>   
    <tr>
    <th>Stock</th>
      <%@players.each do |p|%>
      <td class="score"><%= p.scores.find_by_game_id(@game.id).stocks%></td>
    <%end%>
    </tr>
    <tr>
	    <th>Bonds</th>
      <%@players.each do |p|%>
	      <td class="bond"><%= p.scores.find_by_game_id(@game.id).bonds%></td>
	    <%end%>
    </tr>
    <tr>
      <th>Real Estate</th>
      <%@players.each do |p|%>
        <td class="real_estate"><%= p.scores.find_by_game_id(@game.id).real_estates%></td>
      <%end%>
    </tr>
    <tr>
      <th>Commodities</th>
      <%@players.each do |p|%>
        <td class="commodity"><%= p.scores.find_by_game_id(@game.id).commodities%></td>
      <%end%>
    </tr>
    <tr>
      <th>Cash</th>
      <%@players.each do |p|%>
        <td class="cash"><%= p.scores.find_by_game_id(@game.id).cash%></td>
      <%end%>
    </tr>      
    <th>Net</th>
      <%@players.each do |p|%>
        <td class="net"><%= p.scores.find_by_game_id(@game.id).net%></td>
      <%end%>
    </tr>

</table>    
<%end%>

app/views/invitations/show.html.erb
<h1>You have been invited to <%= @game.name%> with  </h1>o
<p>Accept the invitation do join the game</p>

<%= link_to "Accept", url_for([@invitation.game, @invitation]), method: :patch %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <nav>
      <h1><%= link_to "Sell'em High", root_path, id: "logo" %></h1>
        <ul class="nav pull-right">
          <li><%= link_to "Leader Board",'#' %></li>
          <% if current_user %>
          <li><%= link_to "Profile", user_path(current_user) %></li>
            <li><%= link_to "Sign out", destroy_path, method: "delete" %></li>
          <% else %>
             <li><%= link_to ("Sign Up"), new_user_path %></li>
             <li><%= link_to "sign in", login_path, id: "signin"%></li>
          <% end%>
        </ul>
      </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Turnt</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Nova+Square' rel='stylesheet' type='text/css'>
</head>
<body class="<%= @home_page ? 'homepage' : ''%>">
 <%= render 'layouts/header' %>
<%= yield %>

</body>
</html>

app/views/scores/new.html.erb
<h1>Invite People</h1>
<%= form_tag("/players") do %>
  <%= label_tag(:q, "Search for users:") %>
  <%= text_field_tag(:username) %>
  <%= submit_tag("Search") %>
<% end %>

<% @users.each do |u|%>
  <li><%= u.username %><%=link_to("Invite Player", root_path)%></li>
<%end%>

app/views/users/new.html.erb
<div class="container">
  <h1>Sign Up to Play </h1>
    <ul id="new_user_list">
  	<%= form_for @user, :id => "first" do |f| %>
  	<li>
      <%= f.label :email %>
  	  <%= f.text_field :email %>
    </li>  
     <%if @user.errors.messages[:email] %>
       <%@user.errors.messages[:email].each do |e|%>
         <li><%= 'email ' + e%></li>
       <%end%>
     <%end%> 
    <li>
  	  <%= f.label :username %>
  	  <%= f.text_field :username%>
    </li>
  	<%if @user.errors[:username] %>
       <%@user.errors.messages[:username].each do |e|%>
         <li><%='username '+ e%></li>
       <%end%>
     <%end%> 
    <li>
  	  <%= f.label :password%>
  	  <%= f.text_field :password %>
    </li>  
  	<%if @user.errors[:password] %>
      <%@user.errors.messages[:password].each do |e|%>
        <li><%="password " + e%></li>
       <%end%>
     <%end%> 
  	<li><%= f.submit %></li>
  <% end%>
  </ul>
</div>

app/views/users/search.html.erb
<%if @users ==[]%>
  <p> There are no users with that name </p>
  <h1>Invite People</h1>
  <%= form_tag("/players") do %>
  <%= label_tag(:q, "Search for users:") %>
  <%= text_field_tag(:username) %>
  <%= hidden_field_tag(:game, @game.id)%>
  <%= submit_tag("Search") %>
<% end %>

<% else%>
<% @users.each do |u|%>
  <li>
  <%= u.username %><%=form_tag(game_scores_path(@game)) do%>
  <%= hidden_field_tag("user_id", u.id )%>
  <%= submit_tag("Invite Player")%>
  <% end %>

  </li>
<%end%>

<%end%>
<table class="player">
  <thead>
    <tr class="users">
      <th>Players</th>
      <%@players.each do |p|%>
      <th><%= p.username%></th>
      <% end%>  
    </tr>
 </thead>   
    <tr>
    <th>Stock</th>
      <%@players.each do |p|%>
      <td class="score"><%= p.scores.find_by_game_id(@game.id).stocks%></td>
    <%end%>
    </tr>
    <tr>
	    <th>Bonds</th>
      <%@players.each do |p|%>
	      <td class="bond"><%= p.scores.find_by_game_id(@game.id).bonds%></td>
	    <%end%>
    </tr>
    <tr>
      <th>Real Estate</th>
      <%@players.each do |p|%>
        <td class="real_estate"><%= p.scores.find_by_game_id(@game.id).real_estates%></td>
      <%end%>
    </tr>
    <tr>
      <th>Commodities</th>
      <%@players.each do |p|%>
        <td class="commodity"><%= p.scores.find_by_game_id(@game.id).commodities%></td>
      <%end%>
    </tr>
    <tr>
      <th>Cash</th>
      <%@players.each do |p|%>
        <td class="cash"><%= p.scores.find_by_game_id(@game.id).cash%></td>
      <%end%>
    </tr>      
    <th>Net</th>
      <%@players.each do |p|%>
        <td class="net"><%= p.scores.find_by_game_id(@game.id).net%></td>
      <%end%>
    </tr>

</table>   

app/views/users/show.html.erb
<h1>Welcome <%= @user.username %></h1>
<%=link_to("Search Games",'/search')%>
<%=link_to("Create a Game",new_game_path)%>
  <p>Game Requests</p>
  <ul id="requests">
  <%@requests.each do |i|%>
    <li><%= i.game.name%><%= link_to("accept", game_score_path(i.game,i), html_options = {method: "patch"})%></li>
  <%end%>
  </ul>

  <p>On Going Games</p>
  <ul id="ongoing">
  <%@ongoing.each do |i|%>
    <li><%= link_to(i.game.name, game_path(i.game.id))%></li>
  <%end%>
  </ul>

  <ul id="finished">
  <p>Past Games</p>

  <%@finished.each do |i|%>
    <li><%= link_to(i.game.name, game_path(i.game.id))%></li>
  <%end%>
  </ul>

app/views/welcome/index.html.erb
<div class="container">
  <h1>Sell'em High</h1>
  <%= link_to ("Sign Up"), new_user_path %>
  <%= link_to ("Login"), login_path%>
</div>